package com.rjz.kotlindragger2demo

import android.app.Application
import com.rjz.kotlindragger2demo.dragger.AppComponent
import com.rjz.kotlindragger2demo.dragger.AppModule
import com.rjz.kotlindragger2demo.dragger.DaggerAppComponent

open class MyApplication : Application() {

    private var appComponent: AppComponent? = null

    override fun onCreate() {
        super.onCreate()

        // create AppComponent and AppModule clas then
        // compile project . after this all below 2 lines .
        // "DaggerAppComponent" will generated by compiling....

        //1
       appComponent = DaggerAppComponent.builder()
            .appModule(AppModule(this)).build()

        appComponent?.inject(this)
    }

    //2
    open fun getAppComponent(): AppComponent? {
        return appComponent
    }
}